#!/usr/bin/env bash
# DocVault - a Keycloak proof-of-concept lab.
# Copyright (C) 2026 Magnus Johansson
# SPDX-License-Identifier: GPL-3.0-or-later
# See the LICENSE file for the full licence text.

# Applies - or, with --check, verifies - the SPDX licence header on every
# hand-written source file in the repo.
#
# A file with no header is a file whose licence a reader has to guess. `--check`
# is what CI runs, so a new source file that skips the header fails the build
# instead of shipping unmarked.
#
#   tools/license-header.sh           # add the header wherever it is missing
#   tools/license-header.sh --check   # list offenders, exit 1, change nothing
#
# The include/exclude lists below are the single source of truth for "which
# files carry a header". JSON is absent on purpose: it has no comment syntax at
# all, so those projects declare the licence in package.json's `license` field.
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

PROJECT="DocVault - a Keycloak proof-of-concept lab."
HOLDER="Copyright (C) 2026 Magnus Johansson"
SPDX="SPDX-License-Identifier: GPL-3.0-or-later"
POINTER="See the LICENSE file for the full licence text."

# Matched against the first few lines only, so a file that merely *mentions*
# SPDX further down is not mistaken for one that carries a header.
MARKER="SPDX-License-Identifier"

# Generated, vendored, or platform scaffold: not ours to mark.
EXCLUDE_GLOBS=(
  'infra/local/realm-export/*'                   # generated by `make export-realm`
  'apps/mobile-flutter/ios/*'                    # Xcode scaffold
  'apps/mobile-flutter/android/*.kts'            # Gradle scaffold
  'apps/mobile-flutter/android/*/*.kts'
  'apps/mobile-flutter/android/gradle/*'
  'apps/mobile-flutter/android/app/src/*/res/*'  # Android resource scaffold
  'apps/mobile-flutter/android/app/src/*/AndroidManifest.xml'
  'apps/mobile-flutter/pubspec.yaml'
  'apps/mobile-flutter/analysis_options.yaml'
  '.github/FUNDING.yml'                          # GitHub metadata, not source
  '*.example'                                    # copy-me template; would land in every .env
)

# Extension -> comment style. Anything unmapped is skipped.
style_for() {
  case "$1" in
    *.cs|*.ts|*.tsx|*.js|*.dart|*.kt)             echo slash ;;
    *.tf|*.tfvars|*.sh|*.yml|Makefile|Dockerfile|*/Dockerfile) echo hash ;;
    *.html|*.vue|*.xaml)                          echo xml ;;
    *.css)                                        echo css ;;
    *)                                            echo "" ;;
  esac
}

render() {
  case "$1" in
    slash) printf '// %s\n// %s\n// %s\n// %s\n'          "$PROJECT" "$HOLDER" "$SPDX" "$POINTER" ;;
    hash)  printf '# %s\n# %s\n# %s\n# %s\n'              "$PROJECT" "$HOLDER" "$SPDX" "$POINTER" ;;
    xml)   printf '<!--\n  %s\n  %s\n  %s\n  %s\n-->\n'   "$PROJECT" "$HOLDER" "$SPDX" "$POINTER" ;;
    css)   printf '/*\n * %s\n * %s\n * %s\n * %s\n */\n' "$PROJECT" "$HOLDER" "$SPDX" "$POINTER" ;;
  esac
}

# How many leading lines must stay above the header. Three things insist on
# being the very first bytes of a file and break silently if displaced.
prefix_lines() {
  case "$(head -1 "$1")" in
    '#!'*)                     echo 1 ;;  # shebang
    '<!doctype'*|'<!DOCTYPE'*) echo 1 ;;  # doctype, or the browser drops to quirks mode
    '<?xml'*)                  echo 1 ;;  # XML declaration
    *)                         echo 0 ;;
  esac
}

excluded() {
  local f=$1 glob
  for glob in "${EXCLUDE_GLOBS[@]}"; do
    # shellcheck disable=SC2053  # deliberate glob match, not a string compare
    [[ $f == $glob ]] && return 0
  done
  return 1
}

has_header() { head -12 "$1" | grep -q "$MARKER"; }

insert_header() {
  local f=$1 style=$2 keep tmp
  keep=$(prefix_lines "$f")
  tmp=$(mktemp)
  {
    if [ "$keep" -gt 0 ]; then head -n "$keep" "$f"; fi
    render "$style"
    # Only add a separating blank line if the file does not already start with one.
    if [ -n "$(sed -n "$((keep + 1))p" "$f")" ]; then echo; fi
    tail -n "+$((keep + 1))" "$f"
  } > "$tmp"
  cat "$tmp" > "$f"   # write through, so the executable bit and inode survive
  rm -f "$tmp"
}

# The whole body lives in a function so that bash parses it before any of it
# runs. This script is itself one of the files it rewrites, and prepending five
# lines to a script bash is still reading shifts its file offset - it then
# resumes mid-line and executes garbage. Parsing first, then `exit` on the same
# line as the call, means nothing is ever read from the file after it changes.
main() {
  check_only=false
  case "${1:-}" in
    --check) check_only=true ;;
    '')      ;;
    *)       echo "usage: $0 [--check]" >&2; exit 2 ;;
  esac

  missing=()
  changed=0

  while IFS= read -r f; do
    [ -f "$f" ] || continue
    excluded "$f" && continue
    style=$(style_for "$f")
    [ -n "$style" ] || continue
    has_header "$f" && continue

    if $check_only; then
      missing+=("$f")
    else
      insert_header "$f" "$style"
      changed=$((changed + 1))
    fi
  done < <(git ls-files)

  if $check_only; then
    if [ ${#missing[@]} -gt 0 ]; then
      echo "Missing the $SPDX header:" >&2
      printf '  %s\n' "${missing[@]}" >&2
      echo >&2
      echo "Fix with: tools/license-header.sh" >&2
      exit 1
    fi
    echo "All source files carry the licence header."
  else
    echo "Added the licence header to $changed file(s)."
  fi
}

main "$@"; exit 0
